export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAILURE = 'FETCHING_POSTS_FAILURE';

export const FETCHING_TWEETS = 'FETCHING_TWEETS';
export const FETCHING_TWEETS_SUCCESS = 'FETCHING_TWEETS_SUCCESS';
export const FETCHING_TWEETS_FAILURE = 'FETCHING_TWEETS_FAILURE';

export const FETCHING_NEWS = 'FETCHING_NEWS';
export const FETCHING_NEWS_SUCCESS = 'FETCHING_TWEETS_NEWS';
export const FETCHING_NEWS_FAILURE = 'FETCHING_TWEETS_NEWS';

export const FETCHING_BASE_DATA = 'FETCHING_BASE_DATA';
export const FETCHING_BASE_DATA_SUCCESS = 'FETCHING_BASE_DATA_SUCCESS';
export const FETCHING_BASE_DATA_FAILURE = 'FETCHING_BASE_DATA_FAILURE';
